api_platform:
    title: 'LogicTraders REST API'
    description: 'https://api.logictraders.com'
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Dto']
    patch_formats:
        json: ['application/merge-patch+json']

    eager_loading:
        force_eager: false

    collection:
        pagination:
            client_items_per_page: true
            maximum_items_per_page: 100

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
